apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: sjm-5005-demo-python
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: artifactory-docker-artifactory-jcr2.apps.rosa.rhtap-services.xmdt.p3.openshiftapps.com/rhtap/sjm-5005-demo-python:117432b8f8345b06833ea2ba502f8a7e42e077f4@sha256:103c4661fb4794049dab7511a5ccd34a4c44ea5b9b53e48e7888c0144819e28f
          name: container-image
